"""empty message

Revision ID: 33fa0a3389c7
Revises: 1485f282d2e1
Create Date: 2022-09-28 05:28:11.112164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fa0a3389c7'
down_revision = '1485f282d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('nascimennto', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aluno', 'nascimennto')
    # ### end Alembic commands ###
